### ISSUE TITLE
Add support for include files

### ISSUE THREAD

**Issue by bdarcus** [bdarcus/oxr#5]
Hi,
thanks, I will try it... about the multi-document.
Yes, e.g. I have a main dockument and the chapters in a subfolder
<img width="443" alt="image" src="https://user-images.githubusercontent.com/3047695/174425146-be40d7db-e1a1-4a9e-9c67-ba4806a96207.png">
<img width="499" alt="image" src="https://user-images.githubusercontent.com/3047695/174425151-d409f824-4b61-4938-9011-f960330acddb.png">
And within the text directory one could have something like:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/3047695/174425157-d9200fdc-fd29-4866-b72b-fd7a88a8ef92.png">
So, no I would not say that all open org files is the best approach (usually I have plenty of org files open, which are not relevant for the document).

There could be a few other options:
1) one needs to define a `main`-org-file (which would be the one with the includes above), but I am not sure if the includes are recognized.
2) The  kind of (recursive) grepping takes place in all org-files in the current directory of the current file (this would work with the setup above).
3) one defines a directory where the kind of grepping taks place

Thank you very much!

_Originally posted by @fab6 in https://github.com/bdarcus/oxr/issues/3#issuecomment-1159370942_

**Comment by bdarcus** [comment]
Seems, @fab6, the best approach would just be to open the include files in temp buffers, and parse their targets?

**Comment by fab6** [comment]
not exactly sure, what a temp buffer is, but this is a certain minor mode and one would parse all of these, then it sounds quite practical

**Comment by bdarcus** [comment]
It just means it would open the files and parse them without the user being
aware. A temp buffer is effectively a hidden buffer.
